@id = b47e6226-35ce-4557-8050-937f4b99d455

PUT http://localhost:5276/breakfasts/{{id}}
Content-Type: application/json

{
    "name": "Vegan Moonlight",
    "description": "Vegan everything! Join us for a healthy breakfast..",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}