@id = 2759a1b8-82a4-4373-bc84-127c97d69b47

PUT http://localhost:5276/breakfasts/{{id}}
Content-Type: application/json

{
    "name": "Vegan Moonlight",
    "description": "Vegan everything! Join us for a healthy breakfast..",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}